packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bufferutil: true
  electron: true
  es5-ext: false
  esbuild: true
  prisma: true
  sharp: true
  utf-8-validate: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - 'electron'
  - 'prisma'
  - 'sharp'
